# Flight Price Dataset

source of the dataset: check the dataset info below
https://www.kaggle.com/datasets/shubhambathwal/flight-price-prediction

## EDA and Feature Engineering of the dataset

Aim: Learn while performing EDA and feature engineering on this dataset, to understand the processes before a data can be used for modeling or prediction

### FEATURES
The various features of the cleaned dataset are explained below:
1) Airline: The name of the airline company is stored in the airline column. It is a categorical feature having 6 different airlines.
2) Flight: Flight stores information regarding the plane's flight code. It is a categorical feature.
3) Source City: City from which the flight takes off. It is a categorical feature having 6 unique cities.
4) Departure Time: This is a derived categorical feature obtained created by grouping time periods into bins. It stores information about the departure time and have 6 unique time labels.
5) Stops: A categorical feature with 3 distinct values that stores the number of stops between the source and destination cities.
6) Arrival Time: This is a derived categorical feature created by grouping time intervals into bins. It has six distinct time labels and keeps information about the arrival time.
7) Destination City: City where the flight will land. It is a categorical feature having 6 unique cities.
8) Class: A categorical feature that contains information on seat class; it has two distinct values: Business and Economy.
9) Duration: A continuous feature that displays the overall amount of time it takes to travel between cities in hours.
10)Days Left: This is a derived characteristic that is calculated by subtracting the trip date by the booking date.
11) Price: Target variable stores information of the ticket price.

In [187]:
# All the libraries imported will be here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import openpyxl
from sklearn.preprocessing import OneHotEncoder
%matplotlib inline 
# matplotlib inline is a magic command that configures Matplotlib to display plots directly beneath your code cells inside Jupyter Notebooks or IPython interfaces, instead of opening them in a separate pop-up window

In [188]:
df=pd.read_excel("flight_price.xlsx")
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [189]:
""" here we can see many features, each column has its own varied unclean data which we will be dealing with column by column"""

' here we can see many features, each column has its own varied unclean data which we will be dealing with column by column'

In [190]:
#getting basic info of the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [191]:
# we can see there are 11 columns with 10683 entries and all are object type only last one is integer type.
df.head()
# now we will take each feature one by one

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [192]:
# starting Feature Engineering with date of journey
df['Date']=df['Date_of_Journey'].str.split("/").str[0] #storing the DD in the date column
df['Month']=df['Date_of_Journey'].str.split("/").str[1] #storing the MM in the month column
df['Year']=df['Date_of_Journey'].str.split("/").str[2] #storing the YYYY in the date column
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03,2019

In [193]:
df.info()
# we can observe that the tree new columns created are also object type, we will be converting them to int class

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  object
 12  Month            10683 non-null  object
 13  Year             10683 non-null  object
dtypes: int64(1), object(3), str(10)
memory usage: 1.1+ MB

In [194]:
df['Date']=df['Date'].astype(int)
df['Month']=df['Month'].astype(int)
df['Year']=df['Year'].astype(int)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), str(10)
memory usage: 1.1 MB

In [195]:
# now we can drom the column "Date_of_Journey"
df.drop('Date_of_Journey', axis=1, inplace=True)
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

In [196]:
# now handling the "Arrival_Time"
'''
df['Arrival_hour']=df['Arrival_Time'].str.split(":").str[0]
df['Arrival_min']=df['Arrival_Time'].str.split(":").str[1]
df.head(2)
'''
# applying this as is would create a problem wherein in Arrival_min we will also be getting some extra data to deal with that we will be devising a lambda function

'\ndf[\'Arrival_hour\']=df[\'Arrival_Time\'].str.split(":").str[0]\ndf[\'Arrival_min\']=df[\'Arrival_Time\'].str.split(":").str[1]\ndf.head(2)\n'

In [197]:
df['Arrival_Time']=df['Arrival_Time'].apply(lambda x:x.split(' ')[0]) #deals with extra samaan 
df['Arrival_hour']=df['Arrival_Time'].str.split(":").str[0]
df['Arrival_min']=df['Arrival_Time'].str.split(":").str[1]
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019,13,15

In [198]:
df["Arrival_hour"]=df['Arrival_hour'].astype(int)
df["Arrival_min"]=df['Arrival_min'].astype(int)

In [199]:
df.drop('Arrival_Time',axis=1, inplace=True)
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15

In [200]:
# similarly with departure time
df['Dep_Time']=df['Dep_Time'].apply(lambda x:x.split(' ')[0]) #deals with extra samaan 
df['Dep_hour']=df['Dep_Time'].str.split(":").str[0]
df['Dep_min']=df['Dep_Time'].str.split(":").str[1]
df["Dep_hour"]=df['Dep_hour'].astype(int)
df["Dep_min"]=df['Dep_min'].astype(int)
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15,5,50

In [201]:
df.drop('Dep_Time',axis=1, inplace=True)
df.head(2)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,13,15,5,50

In [202]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Duration         10683 non-null  str
 5   Total_Stops      10682 non-null  str
 6   Additional_Info  10683 non-null  str
 7   Price            10683 non-null  int64
 8   Date             10683 non-null  int64
 9   Month            10683 non-null  int64
 10  Year             10683 non-null  int64
 11  Arrival_hour     10683 non-null  int64
 12  Arrival_min      10683 non-null  int64
 13  Dep_hour         10683 non-null  int64
 14  Dep_min          10683 non-null  int64
dtypes: int64(8), str(7)
memory usage: 1.2 MB

In [203]:
# Let us now deal with some categorical features, starting with Total_Stops
df.Total_Stops.unique()

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [204]:
# to check how many null values are there
df[df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480,6,5,2019,9,25,9,45

In [205]:
# we can see only one Nan value is there and this variable we can replace with the mode value (generaly how categoricals are dealt)
df['Total_Stops'].mode()

0    1 stop
Name: Total_Stops, dtype: str

In [206]:
# dealing with all variables including nan we used this system here as from general knowledge we know more the number of stops higher might be the price
df['Total_Stops']=df['Total_Stops'].map({'non-stop':0, '2 stops':2, '1 stop':1, '3 stops':3,'4 stops':4, np.nan:1})

In [207]:
df[df['Total_Stops'].isnull()]

Empty DataFrame
Columns: [Airline, Source, Destination, Route, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Arrival_hour, Arrival_min, Dep_hour, Dep_min]
Index: []

In [208]:
# we can drop route as we have source and destination and also the time of journey so redundant
df.drop("Route", axis=1, inplace=True)

In [209]:
df.head(2)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50

In [210]:
# handling duration

#in our duration column we have one pplace where the duration in only 5m thus our following codes might not work:
'''
df['duration_hr']=df['Duration'].str.split(' ').str[0].str.split('h').str[0].fillna('0')
df['duration_min']=df['Duration'].str.split(' ').str[1].str.split('m').str[0].fillna('0')
df['duration_hr']=df['duration_hr'].astype(int)
df['duration_min']=df['duration_min'].astype(int)
df.head(2)
'''

df['Duration']=np.where(df['Duration']=='5m','0h 5m',df['Duration'])
df[df['Duration']=='5m']

Empty DataFrame
Columns: [Airline, Source, Destination, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Arrival_hour, Arrival_min, Dep_hour, Dep_min]
Index: []

In [211]:
# As we can see we have handled the isuue now we can use our original code
df['duration_hr']=df['Duration'].str.split(' ').str[0].str.split('h').str[0].fillna('0')
df['duration_min']=df['Duration'].str.split(' ').str[1].str.split('m').str[0].fillna('0')
df['duration_hr']=df['duration_hr'].astype(int)
df['duration_min']=df['duration_min'].astype(int)
df.head(2)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hr,duration_min
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7,25

In [212]:
df['Total_Duration']=(df['duration_hr']*60)+df['duration_min']
#this will give us the total mins taken by our flight which is a much better indicator
df.head(2)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hr,duration_min,Total_Duration
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2,50,170
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7,25,445

In [213]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Duration         10683 non-null  str
 4   Total_Stops      10683 non-null  int64
 5   Additional_Info  10683 non-null  str
 6   Price            10683 non-null  int64
 7   Date             10683 non-null  int64
 8   Month            10683 non-null  int64
 9   Year             10683 non-null  int64
 10  Arrival_hour     10683 non-null  int64
 11  Arrival_min      10683 non-null  int64
 12  Dep_hour         10683 non-null  int64
 13  Dep_min          10683 non-null  int64
 14  duration_hr      10683 non-null  int64
 15  duration_min     10683 non-null  int64
 16  Total_Duration   10683 non-null  int64
dtypes: int64(12), str(5)
memory usage: 1.4 MB

In [214]:
#nor let us get rid of redundant colums
df.drop(['Duration','duration_hr','duration_min'], axis=1, inplace=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Total_Stops      10683 non-null  int64
 4   Additional_Info  10683 non-null  str
 5   Price            10683 non-null  int64
 6   Date             10683 non-null  int64
 7   Month            10683 non-null  int64
 8   Year             10683 non-null  int64
 9   Arrival_hour     10683 non-null  int64
 10  Arrival_min      10683 non-null  int64
 11  Dep_hour         10683 non-null  int64
 12  Dep_min          10683 non-null  int64
 13  Total_Duration   10683 non-null  int64
dtypes: int64(10), str(4)
memory usage: 1.1 MB

In [215]:
# remainingn variables and their values which are mostly categorical only

print(df.Airline.unique())
print(df.Source.unique())
print(df.Destination.unique())
print(df.Additional_Info.unique())

<StringArray>
[                           'IndiGo',                         'Air India',
                       'Jet Airways',                          'SpiceJet',
                 'Multiple carriers',                             'GoAir',
                           'Vistara',                          'Air Asia',
           'Vistara Premium economy',              'Jet Airways Business',
 'Multiple carriers Premium economy',                            'Trujet']
Length: 12, dtype: str
<StringArray>
['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai']
Length: 5, dtype: str
<StringArray>
['New Delhi', 'Banglore', 'Cochin', 'Kolkata', 'Delhi', 'Hyderabad']
Length: 6, dtype: str
<StringArray>
[                     'No info',  'In-flight meal not included',
 'No check-in baggage included',              '1 Short layover',
                      'No Info',               '1 Long layover',
              'Change airports',               'Business class',
               'Red-eye flight',               '2 Long layover']
Length: 10, dtype: str

In [216]:
#since they are not very large data we will be using oneHotEncoder for them
encoder=OneHotEncoder()

In [217]:
encoder.fit_transform(df[['Airline','Source','Destination']]).toarray()

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(10683, 23))

In [218]:
df['Additional_Info']=np.where(df['Additional_Info']=='No info','No Info',df['Additional_Info'])
encoded_df=pd.DataFrame(encoder.fit_transform(df[['Airline','Source','Destination','Additional_Info']]).toarray(),columns=encoder.get_feature_names_out())
encoded_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 32 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Airline_Air Asia                              10683 non-null  float64
 1   Airline_Air India                             10683 non-null  float64
 2   Airline_GoAir                                 10683 non-null  float64
 3   Airline_IndiGo                                10683 non-null  float64
 4   Airline_Jet Airways                           10683 non-null  float64
 5   Airline_Jet Airways Business                  10683 non-null  float64
 6   Airline_Multiple carriers                     10683 non-null  float64
 7   Airline_Multiple carriers Premium economy     10683 non-null  float64
 8   Airline_SpiceJet                              10683 non-null  float64
 9   Airline_Trujet                                10683 non-null  float64
 10  Airline_Vistara                               10683 non-null  float64
 11  Airline_Vistara Premium economy               10683 non-null  float64
 12  Source_Banglore                               10683 non-null  float64
 13  Source_Chennai                                10683 non-null  float64
 14  Source_Delhi                                  10683 non-null  float64
 15  Source_Kolkata                                10683 non-null  float64
 16  Source_Mumbai                                 10683 non-null  float64
 17  Destination_Banglore                          10683 non-null  float64
 18  Destination_Cochin                            10683 non-null  float64
 19  Destination_Delhi                             10683 non-null  float64
 20  Destination_Hyderabad                         10683 non-null  float64
 21  Destination_Kolkata                           10683 non-null  float64
 22  Destination_New Delhi                         10683 non-null  float64
 23  Additional_Info_1 Long layover                10683 non-null  float64
 24  Additional_Info_1 Short layover               10683 non-null  float64
 25  Additional_Info_2 Long layover                10683 non-null  float64
 26  Additional_Info_Business class                10683 non-null  float64
 27  Additional_Info_Change airports               10683 non-null  float64
 28  Additional_Info_In-flight meal not included   10683 non-null  float64
 29  Additional_Info_No Info                       10683 non-null  float64
 30  Additional_Info_No check-in baggage included  10683 non-null  float64
 31  Additional_Info_Red-eye flight                10683 non-null  float64
dtypes: float64(32)
memory usage: 2.6 MB

In [219]:
#merging the encoded data to our original dataframe
df=pd.merge(df,encoded_df,left_index=True,right_index=True)
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,...,Destination_New Delhi,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_Red-eye flight
0,IndiGo,Banglore,New Delhi,0,No Info,3897,24,3,2019,1,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,Air India,Kolkata,Banglore,2,No Info,7662,1,5,2019,13,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,Jet Airways,Delhi,Cochin,2,No Info,13882,9,6,2019,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,IndiGo,Kolkata,Banglore,1,No Info,6218,12,5,2019,23,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,IndiGo,Banglore,New Delhi,1,No Info,13302,1,3,2019,21,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [220]:
#Finally getting rid of all the categorical data
df.drop(['Airline','Source','Destination','Additional_Info'],axis=1,inplace=True)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 42 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Total_Stops                                   10683 non-null  int64
 1   Price                                         10683 non-null  int64
 2   Date                                          10683 non-null  int64
 3   Month                                         10683 non-null  int64
 4   Year                                          10683 non-null  int64
 5   Arrival_hour                                  10683 non-null  int64
 6   Arrival_min                                   10683 non-null  int64
 7   Dep_hour                                      10683 non-null  int64
 8   Dep_min                                       10683 non-null  int64
 9   Total_Duration                                10683 non-null  int64
 10  Airline_Air Asia                              10683 non-null  float64
 11  Airline_Air India                             10683 non-null  float64
 12  Airline_GoAir                                 10683 non-null  float64
 13  Airline_IndiGo                                10683 non-null  float64
 14  Airline_Jet Airways                           10683 non-null  float64
 15  Airline_Jet Airways Business                  10683 non-null  float64
 16  Airline_Multiple carriers                     10683 non-null  float64
 17  Airline_Multiple carriers Premium economy     10683 non-null  float64
 18  Airline_SpiceJet                              10683 non-null  float64
 19  Airline_Trujet                                10683 non-null  float64
 20  Airline_Vistara                               10683 non-null  float64
 21  Airline_Vistara Premium economy               10683 non-null  float64
 22  Source_Banglore                               10683 non-null  float64
 23  Source_Chennai                                10683 non-null  float64
 24  Source_Delhi                                  10683 non-null  float64
 25  Source_Kolkata                                10683 non-null  float64
 26  Source_Mumbai                                 10683 non-null  float64
 27  Destination_Banglore                          10683 non-null  float64
 28  Destination_Cochin                            10683 non-null  float64
 29  Destination_Delhi                             10683 non-null  float64
 30  Destination_Hyderabad                         10683 non-null  float64
 31  Destination_Kolkata                           10683 non-null  float64
 32  Destination_New Delhi                         10683 non-null  float64
 33  Additional_Info_1 Long layover                10683 non-null  float64
 34  Additional_Info_1 Short layover               10683 non-null  float64
 35  Additional_Info_2 Long layover                10683 non-null  float64
 36  Additional_Info_Business class                10683 non-null  float64
 37  Additional_Info_Change airports               10683 non-null  float64
 38  Additional_Info_In-flight meal not included   10683 non-null  float64
 39  Additional_Info_No Info                       10683 non-null  float64
 40  Additional_Info_No check-in baggage included  10683 non-null  float64
 41  Additional_Info_Red-eye flight                10683 non-null  float64
dtypes: float64(32), int64(10)
memory usage: 3.4 MB

## Completed

Thus we have copleted the Feature Engineering of the data set given to us. Essentially ensuring that the data made sense and the categorical data was converted to numberical form to be ready to feed to our model.

In [225]:
#for comparison let us see the difference berween the two datas
df_original=pd.read_excel('flight_price.xlsx')
df_original.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [226]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 42 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Total_Stops                                   10683 non-null  int64
 1   Price                                         10683 non-null  int64
 2   Date                                          10683 non-null  int64
 3   Month                                         10683 non-null  int64
 4   Year                                          10683 non-null  int64
 5   Arrival_hour                                  10683 non-null  int64
 6   Arrival_min                                   10683 non-null  int64
 7   Dep_hour                                      10683 non-null  int64
 8   Dep_min                                       10683 non-null  int64
 9   Total_Duration                                10683 non-null  int64
 10  Airline_Air Asia                              10683 non-null  float64
 11  Airline_Air India                             10683 non-null  float64
 12  Airline_GoAir                                 10683 non-null  float64
 13  Airline_IndiGo                                10683 non-null  float64
 14  Airline_Jet Airways                           10683 non-null  float64
 15  Airline_Jet Airways Business                  10683 non-null  float64
 16  Airline_Multiple carriers                     10683 non-null  float64
 17  Airline_Multiple carriers Premium economy     10683 non-null  float64
 18  Airline_SpiceJet                              10683 non-null  float64
 19  Airline_Trujet                                10683 non-null  float64
 20  Airline_Vistara                               10683 non-null  float64
 21  Airline_Vistara Premium economy               10683 non-null  float64
 22  Source_Banglore                               10683 non-null  float64
 23  Source_Chennai                                10683 non-null  float64
 24  Source_Delhi                                  10683 non-null  float64
 25  Source_Kolkata                                10683 non-null  float64
 26  Source_Mumbai                                 10683 non-null  float64
 27  Destination_Banglore                          10683 non-null  float64
 28  Destination_Cochin                            10683 non-null  float64
 29  Destination_Delhi                             10683 non-null  float64
 30  Destination_Hyderabad                         10683 non-null  float64
 31  Destination_Kolkata                           10683 non-null  float64
 32  Destination_New Delhi                         10683 non-null  float64
 33  Additional_Info_1 Long layover                10683 non-null  float64
 34  Additional_Info_1 Short layover               10683 non-null  float64
 35  Additional_Info_2 Long layover                10683 non-null  float64
 36  Additional_Info_Business class                10683 non-null  float64
 37  Additional_Info_Change airports               10683 non-null  float64
 38  Additional_Info_In-flight meal not included   10683 non-null  float64
 39  Additional_Info_No Info                       10683 non-null  float64
 40  Additional_Info_No check-in baggage included  10683 non-null  float64
 41  Additional_Info_Red-eye flight                10683 non-null  float64
dtypes: float64(32), int64(10)
memory usage: 3.4 MB